### ISSUE TITLE
knn.fit(training) throws an exception

### ISSUE THREAD

**Issue by akshaybhatt14495** [saurfang/spark-knn#32]
followed whatever was there
val training = MLUtils.loadLibSVMFile(sc, "data/mllib/sample_libsvm_data.txt").toDF()
val knn = new KNNClassifier()
  .setTopTreeSize(training.count().toInt / 500)
  .setK(10)
 TopTreeSize is invalid 0 (since total count of training sample is 100)
let say we set manually TreeSize as 1
then it throws an exception while running knn.fit(training)

java.util.NoSuchElementException: Failed to find a default value for inputCols
  at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:652)
  at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:652)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.ml.param.Params$class.getOrDefault(params.scala:651)
  at org.apache.spark.ml.PipelineStage.getOrDefault(Pipeline.scala:42)
  at org.apache.spark.ml.param.Params$class.$(params.scala:658)
  at org.apache.spark.ml.PipelineStage.$(Pipeline.scala:42)
  at org.apache.spark.ml.knn.KNN.fit(KNN.scala:383)

**Comment by kaushikacharya** [comment]
Hi,
  If you at the example:
https://github.com/saurfang/spark-knn/blob/master/spark-knn-examples/src/main/scala/com/github/saurfang/spark/ml/knn/examples/MNIST.scala

For KNNClassifier object it sets the two column names i.e. features,
prediction

.setFeaturesCol("pcaFeatures")
.setPredictionCol("predicted")
These seems to be missing in your case.

**Comment by akshaybhatt14495** [comment]
Hey thanks for response, actually i need k nearest neighbors (KNN) , so for that do we need classification in dataset (i.e. first entry in each case as 0 or 1)??

**Comment by akshaybhatt14495** [comment]
@kaushikacharya  i'm talking about KNN.scala

**Comment by akshaybhatt14495** [comment]
Got another error in command knn.fit(training)

Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Column features must be of type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7 but was actually org.apache.spark.mllib.linalg.VectorUDT@f71b0bce.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.ml.util.SchemaUtils$.checkColumnType(SchemaUtils.scala:42)
	at org.apache.spark.ml.PredictorParams$class.validateAndTransformSchema(Predictor.scala:51)
	at org.apache.spark.ml.classification.Classifier.org$apache$spark$ml$classification$ClassifierParams$$super$validateAndTransformSchema(Classifier.scala:58)

**Comment by akshaybhatt14495** [comment]
@kaushikacharya  spark version is 2.2.0

**Comment by kaushikacharya** [comment]
Have a look at
https://github.com/saurfang/spark-knn/blob/master/project/Dependencies.scala
val sparktest = "org.apache.spark" %% "spark-core" % "2.1.0"  % "test" classifier "tests"

My understanding is that this repository is updated for spark 2.1.0
You using 2.2.0 could be the reason for the errors which you are facing.

**Comment by akshaybhatt14495** [comment]
i changed my version and now working with spark 2.1.0, then also got same error,

**Comment by akshaybhatt14495** [comment]
Ok, i used MLUtils function convertVectorColumnsFromML(training, "features")
so then got new error  for sample data given in sample_libsvm_data.txt

java.lang.IllegalArgumentException: requirement failed: Sampling fraction (1.01) must be on interval [0, 1]
  at scala.Predef$.require(Predef.scala:224)
  at org.apache.spark.util.random.BernoulliSampler.<init>(RandomSampler.scala:147)
  at org.apache.spark.rdd.RDD$$anonfun$sample$2.apply(RDD.scala:496)
  at org.apache.spark.rdd.RDD$$anonfun$sample$2.apply(RDD.scala:491)

**Comment by kaushikacharya** [comment]
You are facing the same issue as:
https://github.com/saurfang/spark-knn/issues/21

Your error says that:
Sampling fraction (1.01) must be on interval [0, 1]

sampling fraction needs to be <= 1

I would suggest first try running on mnist data (mnist.bz2) from
https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass/
Put this data in your data folder and run the mnist scala example.



On Thu, Jan 11, 2018 at 10:43 AM, akshaybhatt14495 <notifications@github.com
