### ISSUE TITLE
Exception occurred when initializing new KNNRegression()

### ISSUE THREAD

**Issue by ashanwijenayake** [saurfang/spark-knn#42]
val knn = new KNNRegression().setTopTreeSize(df.count().toInt / 500)
                                     .setFeaturesCol("features")
                                     .setPredictionCol("predicted")
                                     .setK(1)

This throws the following exception,

Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.param.shared.HasInputCols$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by sagnik-rzt** [comment]
It's not able to load your KNN object, do you have the spark classpath pointing to your JARs?

**Comment by ashanwijenayake** [comment]
> It's not able to load your KNN object, do you have the spark classpath pointing to your JARs?

Yes. Spark class path is in order.

**Comment by ntaherkhani** [comment]
I am getting  same error. do you have any update?

**Comment by ashanwijenayake** [comment]
> I am getting same error. do you have any update?

I couldn't find a solution so I had to move on.

**Comment by ntaherkhani** [comment]
> > I am getting same error. do you have any update?
> 
> I couldn't find a solution so I had to move on.

what alternative did you use?

**Comment by Alpus** [comment]
I used version '0.3.0' and it seemed to work for me
