### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by tangfei67** [saurfang/spark-knn#5]
I run the example, but get 

Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Sampling fraction (10.0) must be on interval [0, 1]
	at scala.Predef$.require(Predef.scala:233)
	at org.apache.spark.util.random.BernoulliSampler.<init>(RandomSampler.scala:149)
	at org.apache.spark.rdd.RDD$$anonfun$sample$1.apply(RDD.scala:430)
	at org.apache.spark.rdd.RDD$$anonfun$sample$1.apply(RDD.scala:425)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
	at org.apache.spark.rdd.RDD.sample(RDD.scala:425)
	at org.apache.spark.ml.knn.KNN.fit(KNN.scala:317)
	at org.apache.spark.ml.classification.KNNClassifier.train(KNNClassifier.scala:109)
	at org.apache.spark.ml.classification.KNNClassifier.train(KNNClassifier.scala:24)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:90)
	at ict.knn.JavaKNN.main(JavaKNN.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by saurfang** [comment]
This is related to the default value of `TopTreeSize` (1000). It looks like your dataset size is far smaller than that (~100 it seems?). You can reduce the TopTreeSize by call `.setTopTreeSize(1)` as shown in the README. A smarter way to determine default TopTreeSize is definitely on my wish list.
