### ISSUE TITLE
Run problem in Spark 1.6.0

### ISSUE THREAD

**Issue by VictorMikhaylov** [saurfang/spark-knn#6]
If I try run example in Spark 1.6.0 I get exception:

ERROR [apache.spark.executor.Executor:logError  :95  ] - Exception in task 0.0 in stage 7.0 (TID 7)sg
java.lang.NoSuchMethodError: org.apache.spark.ml.classification.MultiClassSummarizer.add(D)Lorg/apache/spark/ml/classification/MultiClassSummarizer;
        at org.apache.spark.ml.classification.KNNClassifier$$anonfun$2.apply(KNNClassifier.scala:91)
        at org.apache.spark.ml.classification.KNNClassifier$$anonfun$2.apply(KNNClassifier.scala:89)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at org.apache.spark.InterruptibleIterator.foldLeft(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
        at org.apache.spark.InterruptibleIterator.aggregate(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1121)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1121)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1122)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1122)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Scala version 2.10.6

**Comment by chy168** [comment]
I got the same problem on spark 1.6.0, any suggestion?

**Comment by palicand** [comment]
I have ran into the same problem. Luckily, recompilation, with setting the dependency to Spark 1.6 fixed the issue.

**Comment by saurfang** [comment]
Sorry for the late response as I have been away from Github for a while. I thought something might have changed but I guess it is just regular binary incompatibility among Spark major versions. Thanks @palicand!

**Comment by gianvi** [comment]
Hi guys, I tryied to run the fit method on a basic model and I (still) got the same error...
from my sbt ...

//knn
resolvers += "Spark Packages Repo" at "https://dl.bintray.com/spark-packages/maven/"


libraryDependencies := Seq(
  "org.apache.spark" % "spark-core_2.10" % "1.6.1",
  "org.apache.spark" % "spark-mllib_2.10" % "1.6.1",
  "org.apache.spark" % "spark-sql_2.10" % "1.6.1",

  "org.scalatest" % "scalatest_2.10" % "2.2.1" % "test",
  "com.databricks" % "spark-csv_2.10" % "1.2.0",

  //knn
  "saurfang" % "spark-knn" % "0.1.0"
}

...how do you fixed?

**Comment by gianvi** [comment]
Actually is working with spark 1.5, but was helpful to have it working with 1.6.

**Comment by saurfang** [comment]
@gianvi Did you recompile `spark-knn` against 1.6?

**Comment by gianvi** [comment]
@saurfang thanks for reply...actually I modified my code to run on 1.5 (I'll try to recompile it later.)
Actually I have 2 issues when I try to fit the model, that I cannot understand from the stack trace:

java.lang.UnsupportedOperationException: empty.min
	at scala.collection.TraversableOnce$class.min(TraversableOnce.scala:209)
	at scala.collection.AbstractTraversable.min(Traversable.scala:105)
	at org.apache.spark.ml.knn.KNN$$anonfun$16.apply(KNN.scala:438)
	at org.apache.spark.ml.knn.KNN$$anonfun$16.apply(KNN.scala:438)
       [...]
This happens with this config (and others) on the model:
      .setK(2)
      .setTopTreeSize(4)
      .setTopTreeLeafSize(2)
      .setSubTreeLeafSize(2)
      .setFeaturesCol("features")
      .setLabelCol("label")
      .setBalanceThreshold(0)
        //.setWeightCol("")
      .setBufferSizeSampleSizes(Array(1,2,3,4,5,6,7,8,9,10))

This happens, instead, with default settings:
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Sampling fraction (11.235955056179776) must be on interval [0, 1]
	at scala.Predef$.require(Predef.scala:233)

Here the stats summary of my features, and the show tables: they are sift elabored keypoints vectors from images.
Actually i didn't had the time to well understand all the parameters of the model, and I just like to run it for some tests...so any help would really appreciate (after this I really would like to understand the metrics that u used)
Thanks in advance

[errorKnn.txt](https://github.com/saurfang/spark-knn/files/305627/errorKnn.txt)

**Comment by gianvi** [comment]
If could help: My train set is composed by 89 (images) represented by featuresvector of size 319
